### ISSUE TITLE
NullPointerException in UploadFilesTask

### ISSUE THREAD

**Issue by buhman** [phora/AndroPTPB#2]
```
D/AndroidRuntime(26703): Shutting down VM
E/AndroidRuntime(26703): FATAL EXCEPTION: main
E/AndroidRuntime(26703): Process: io.github.phora.androptpb, PID: 26703
E/AndroidRuntime(26703): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.github.phora.androptpb.network.UploadData.getServerUrl()' on a null object reference
E/AndroidRuntime(26703):    at io.github.phora.androptpb.activities.MainActivity.addUploads(MainActivity.java:905)
E/AndroidRuntime(26703):    at io.github.phora.androptpb.activities.MainActivity.access$200(MainActivity.java:56)
E/AndroidRuntime(26703):    at io.github.phora.androptpb.activities.MainActivity$UploadFilesTask.onPostExecute(MainActivity.java:351)
E/AndroidRuntime(26703):    at io.github.phora.androptpb.activities.MainActivity$UploadFilesTask.onPostExecute(MainActivity.java:240)
E/AndroidRuntime(26703):    at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime(26703):    at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime(26703):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime(26703):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26703):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(26703):    at android.app.ActivityThread.main(ActivityThread.java:6837)
E/AndroidRuntime(26703):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26703):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26703):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(26703):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Pretty sure this happens because `network.NetworkUtils.getReplaceResult()` returns a null UploadData when `sha1 == null`, which is indeed null because you're looking for `sha1:` in the response, which was replaced by `digest` in ptpb/pb@ae5d8effa3d4986a41aee74409c561e1967db0b4 (sorry about that).

`getReplaceResult` itself looks really terrible; I suggest not trying to parse yaml, and instead passing `Accept: application/json` to get a json response, which you can decode with [JSONTokener](https://developer.android.com/reference/org/json/JSONTokener.html).

**Comment by buhman** [comment]
> get a json response

Oh, looks like you're already doing that in fc11fabe17c7a65be50e85e591812a91ebb467c4.

**Comment by buhman** [comment]
And 5600fc85c97cd0a1d6ca98b99d202aba1bb3d198 ; k then.
